
#spring.profiles.active=dev
#spring.profiles.active=prod
spring.profiles.active=test

spring.jpa.open-in-view=true
spring.jpa.properties.failOnError=true
#spring.devtools.restart.enabled=false
#logging.level.org.springframework=DEBUG

spring.jpa.properties.hibernate.scan_packages=application.entities