# Desativa o Spring Boot Web
spring.main.web-application-type=none

# Desativa o H2 (se estiver configurado no application.properties)
spring.datasource.url=
spring.datasource.driver-class-name=
spring.datasource.username=
spring.datasource.password=
spring.h2.console.enabled=false